version: '2'
 
services:
    db:
        build: docker/mysql
        restart: unless-stopped
        ports:
            - ${MYSQL_PORT}
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ${MYSQL_DATAPATH}:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        links:
            - db
        ports:
            - ${PHPMYADMIN_PORT}
        environment:
            VIRTUAL_HOST: ${VIRTUAL_HOST}
            VIRTUAL_PORT: 81
            LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
networks:
    default:
        external:
            name: ${PROXY_NETWORK}
